services:
  nuxt-composables:
    build: .
    ports:
      - "${APP_PORT:-3002}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NUXT_PUBLIC_APP_ENV: ${NUXT_PUBLIC_APP_ENV:-production}
    restart: unless-stopped
